# Generated by Django 2.2.11 on 2020-08-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20200821_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_location',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='start_trip',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='stop_trip',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.Driver_location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.Start_trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='stop_trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.Stop_trip'),
        ),
    ]
