# Generated by Django 2.2.11 on 2020-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20200821_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver_location',
            old_name='coordinates',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='start_trip',
            old_name='pickup_location_coordinates',
            new_name='pickup_location_lat',
        ),
        migrations.RenameField(
            model_name='stop_trip',
            old_name='pickup_location_coordinates',
            new_name='pickup_location_lat',
        ),
        migrations.AddField(
            model_name='driver_location',
            name='long',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='start_trip',
            name='pickup_location_long',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop_trip',
            name='pickup_location_long',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=16),
            preserve_default=False,
        ),
    ]
