# Generated by Django 2.2.11 on 2020-08-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20200821_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_location',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='driver_location',
            name='long',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
