# Generated by Django 2.2.11 on 2020-08-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20200821_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Country')),
            ],
        ),
        migrations.AlterField(
            model_name='start_trip',
            name='pickup_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Address'),
        ),
        migrations.AlterField(
            model_name='start_trip',
            name='pickup_location_lat',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='start_trip',
            name='pickup_location_long',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stop_trip',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stop_trip',
            name='pickup_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Address'),
        ),
        migrations.AlterField(
            model_name='stop_trip',
            name='pickup_location_lat',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stop_trip',
            name='pickup_location_long',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
