# Generated by Django 2.2.11 on 2020-08-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_auto_20200821_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_location',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Driver_locationtrip', to='trips.Trip'),
        ),
        migrations.AlterField(
            model_name='start_trip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Start_triptrip', to='trips.Trip'),
        ),
        migrations.AlterField(
            model_name='stop_trip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Stop_triptrip', to='trips.Trip'),
        ),
    ]
