# Generated by Django 2.2.11 on 2020-08-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20200821_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_trip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_trip', to='trips.Trip'),
        ),
    ]
