# Generated by Django 2.2.11 on 2020-08-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_auto_20200821_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='trips.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='trips.Country'),
            preserve_default=False,
        ),
    ]
