# Generated by Django 2.2.11 on 2020-08-21 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_auto_20200821_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_trip',
            name='pickup_location_type',
            field=models.CharField(default='Point', max_length=10),
        ),
        migrations.AlterField(
            model_name='stop_trip',
            name='pickup_location_type',
            field=models.CharField(default='Point', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.Car'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
