# Generated by Django 2.2.11 on 2020-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_auto_20200821_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_location',
            name='type',
            field=models.CharField(default='Point', max_length=10),
        ),
    ]
