# Generated by Django 2.2.11 on 2020-08-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_auto_20200823_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_trip',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
