# Generated by Django 2.2.11 on 2020-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_auto_20200823_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='check_code',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Check_code',
        ),
    ]
