# Generated by Django 2.2.11 on 2020-08-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_auto_20200824_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=10),
        ),
    ]
